site_name: Learn Chinese
# site_url: https://.wiki/
site_description: Immersion-based Chinese Learning
site_author: Cashew
# repo_url: https://github.com/yomidevs/yomitan
# repo_name: Yomitan
nav:
  - Home: 'index.md'
  - Preamble: 'preamble.md'
  - Guide: 'guide.md'
  - Setup: 'setup.md'
  - Credits: 'credits.md'
theme:
  name: material
  favicon: assets/icon/yomitan-icon64.png
  logo: assets/icon/yomitan-icon128.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - announce.dismiss
  language: en
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode    
      primary: custom

extra:
  # social:
  #   - icon: fontawesome/brands/discord
  #     link: https://discord.gg/YkQrXW6TXF
  homepage: https://yomitan.wiki/ # todo!
  generator: false

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - git-revision-date-localized
  - social
  - search:
      lang:
        - en
        - ja
  - glightbox:
      manual: true
      width: 70%
      effect: none


extra_css:
  - stylesheets/extra.css
  - stylesheets/homepage.css
